name: Playwright Tests
on:
  push:
    branches: [main, master, feature/run-tests-in-ci]
  pull_request:
    branches: [main, master, feature/run-tests-in-ci]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install 
      - name: Run Playwright tests
        run: yarn run test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30